doctrine_mongodb:
    connections:
        default:
            server: "%env(resolve:MONGODB_URL)%"
            options: {}
    default_database: Ecoride_db
    document_managers:
        default:
            auto_mapping: true