doctrine_mongodb:
    connections:
        default:
            server: "%env(resolve:MONGODB_URL)%"
            options: 
                tls: true
                tlsAllowInvalidCertificates: false
                ssl:
                    # Option explicite pour forcer TLS 1.2
                    sslProtocol: TLSv1_2
    default_database: Ecoride_db
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: attribute 
                    dir: '%kernel.project_dir%/src/Document' 
                    prefix: 'App\Document' 
                    alias: App